// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2526_2121051489_BaiThi.Data.Data;

#nullable disable

namespace _2526_2121051489_BaiThi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620100745_Baithi123")]
    partial class Baithi123
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("_2526_2121051489_BaiThi.Models.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("_2526_2121051489_BaiThi.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
